#!/usr/bin/perl
#Dependencies:
#dd
#losetup
#mkdir
#mount
#debootstrap
#umount
#rmdir

use strict;
use warnings;
use Getopt::Long;
Getopt::Long::Configure ('bundling');

#Check to make sure user is root
my $user = `whoami`;
chomp $user;
if($user ne 'root'){
  print 'Superuser privileges are necessary for some parts of this script; ';
  print 'use sudo.' . "\n";
  exit(1);
}

#################
#  Global Vars  #
#################

#General
my $verbose = 0;
my $help;
my $count = 4;
my $location = './';
my $img_name = 'test';
my $dev_device = 0;
my $mount_dir = 0;
my $clean = 0;

#Debootstrap Options
my $arch = 'i686';
my $apt_include = 'bonnie++';
my $distro = 'gutsy';
my $mirror = 'http://archive.ubuntu.com/ubuntu';


#DD Config Options
my $dd_bs = 1024;
my $dd_count = 1;
my $dd_seek = 1;

GetOptions ('c|count=i' =>\$count,
            'a|arch=s' => \$arch,
            'd|distro=s' => \$distro,
            'l|location=s' => \$location,
            'n|name=s' => \$img_name,
            'm|mirror=s' => \$mirror,
            'ddbs=i' => \$dd_bs,
            's|ddseek=i' => \$dd_seek,
            'h|help' => \$help,
            'v' => $verbose,
            'clean' => $clean);

# Display help
if($help || ($#ARGV+1) != 1){
  print 'Usage: [options] imagename' . "\n";
  print "  -c [count], --count [count]\t\t\tNumber of IMGs to Create\n";
  print "  -a [arch], --arch [arch]\t\t\tArchitecture to Install\n";
  print "  -d [distro], --distro [distro]\t\tDistro to Install\n";
  print "  -l [location], --location [location]\t\tLocation to Create IMGs at\n";
  print "  -m [mirror], --mirror [mirror]\t\tMirror to Intall from\n";
  print "  --ddbs [size]\t\t\t\t\tBS for DD command\n";
  print "  --ddcount [count]\t\t\t\tCount for DD command\n";
  print "  -s [count], --ddseek [count]\t\t\tSeek for DD command\n";
  print "  --clean\t\t\t\tclean old image build\n";
  print "  -v\t\t\t\tverbose\n";
  print "  -h --help\t\t\t\t\tThis.\n";
  exit(1);
}

#################
#  Subroutines  #
#################

my $time =  time();
my $logfilename="creator.log.$img_name.$time";
open(LOGFILE, ">$logfilename") or die("Unable to open logfile: $logfilename");

sub log_info {
  print LOGFILE "$_[0]\n";
  print "$_[0]\n";
}

sub log_fatal {
  print LOGFILE "$_[0]\n";
  clean_env();
  die("$_[0]");
}

sub ex_quiet {
  my($command,$name,$do_not_fatal) = @_;
  if ($name) {
    log_info("TASK: $name");
  }
  if ($verbose) {
    log_info("COMMAND: $command");
  }
  my $ret = `$command 2>&1`;
  if ($? != 0) {
    log_info("OUTPUT: $ret\n");
    if ($do_not_fatal) {
      log_info("ERROR: Return Code $?\n");
    } else {
      log_fatal("ERROR: Return Code $?\n");
    }
  }
  return $ret;
}

sub ex_verbose {
  my($command,$name) = @_;
  if ($name) {
    log_info("TASK: $name");
  }
  if ($verbose) { 
    log_info("COMMAND: $command");
  }
  system("$command");
  if ($? != 0) {
    log_fatal("ERROR: Return Code $?");
  }
}

sub clean_env() {
  ex_quiet('umount $mount_dir', "[CLEAN] Unmounting Temporary Directory");
  ex_quiet('rmdir $mount_dir', "[CLEAN] Removing Temporary Directory");
  if($dev_device) {
    ex_quiet('losetup -d $dev_device', "[CLEAN] Removing Loopback Device");
  } else {
    log_info("[CLEAN] Could not find dev device for losetup -d");
  }
}

#?!?!?!? To copy as .img or all files ?!?!?!?!?!
#copy (whole .img for now)
#my @copy_command;
#for (my $i=1; $i<$count; $i++){
#  push(@copy_command, 'cp ' . $location . $img_name . '.img ' . $location . 
#                      $img_name . '_' . $i . '.img');
#}

###########
#   Run   #
###########

#Parse Command Line vars after options
$img_name = $ARGV[0];
$mount_dir = $location . 'mnt-' . $img_name;
if($clean) {
  clean_env();
  exit(0);
}

ex_quiet('dd if=/dev/zero of=' . $location . $img_name . '.img ' . 'bs=' . 
         $dd_bs . 'K count=' . $dd_count . ' seek=' . $dd_seek,
         "Creating image file");
$dev_device = ex_quiet('losetup -f', "Getting Free Loopback Device");
ex_quiet('losetup ' . $dev_device . ' ' . $location . $img_name,
         "Creating Loopback Block Device");
ex_quiet('mkfs.ext3 ' . $dev_device, "Creating Loopback Block Device");

ex_quiet('mkdir -pf ' . $mount_dir, "Creating Temporary Mount Directory");
ex_verbose('debootstrap --arch ' . $arch . ' --include=' . $apt_include . ' ' . $distro . 
           ' ' . $location . $img_name . ' ' . $mirror, 
           "Creating base guest filesystem");

#foreach (@copy_command) {
#  print 'CREATOR: copy-ing...' . "\n";
#  (system($_) == 0) or die ("copy failed ($?)");
#}  

clean_env();
