#!/bin/bash
kvm \
-m 256 \
-kernel /boot/vmlinuz-2.6.18-6-amd64 \
-initrd /boot/initrd.img-2.6.18-6-amd64 \
-append "root=UUID=c567f8f0-3adf-408a-b2b4-358fb88f5df7 console=tty0 console=ttyS0,115200n8" \
-net nic,vlan=0,macaddr=AA:BB:CC:DD:EE:01 \
-net tap,vlan=0,ifname=tap0,script=./qemu-ifup \
-nographic \
test-pristine.img
#-net nic,vlan=0 \

